### ISSUE TITLE
Tema precisa de um rodapé

### ISSUE THREAD

**Issue by kydrix** [elementaryOSBrasil/eosbrwp#40]
Precisamos desenhar e codificar um rodapé para o tema.

**Comment by cjgomes** [comment]
Eu havia pensado, esqueci de registrar..
poderíamos fazer um rodapé com "parallax" oculto, como na página atual do elementaryos.org
quando o usuário dar scroll na página o rodapé é mostrado.

**Comment by cjgomes** [comment]
ou fazer um rodapé bem simples com uma linha apenas no fundo da página.
